#
# COMP90024 Cluster and Cloud Computing Assignment2 - Team 42 
# 
# Authors: 
#
#  - Haoyu Gao (Student ID: 1141213)
#  - Runqi Zhao (Student ID: 1159719)
#  - Shukai Liu (Student ID: 1233459)
#  - Siyu Liu (Student ID：1094521)
#  - Wenjun Wang (Student ID: 1249890)
#
# Location: Melbourne
#  

- hosts: localhost
  vars_files:
    - host_vars/Melbourne_Research_Cloud.yaml
  gather_facts: true

  roles:
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

# Install Docker and CouchDB for data nodes
- hosts: DataNodes
  vars_files:
    - host_vars/docker_and_couchdb.yaml
  gather_facts: true

  roles:
    - role: nodes-common
    - role: docker-install
    - role: docker-volume-mount
    - role: couchdb-setup

# Perform CouchDB deployment on all hosts except Masternode
- hosts: DataNodes:!Masternode
  vars_files:
    - host_vars/docker_and_couchdb.yaml
  gather_facts: true

  roles:
    - role: couchdb-deployment

# Set up software Twitter Streaming (Harvester) and install tomcat service on all data nodes
- hosts: DataNodes
  vars_files:
    - host_vars/proxy_environment.yaml
  gather_facts: true

  roles:
     - role: twitter-harvester-setup
     - role: tomcat-service-install
     
# Install Docker and set up software Twitter Streaming (Harvester) for processing node
- hosts: ProcessingNode
  vars_files:
    - host_vars/proxy_environment.yaml
  gather_facts: true

  roles:
    - role: nodes-common
    - role: docker-install
    - role: docker-volume-mount
    - role: npm-nodejs-install
    - role: twitter-harvester-setup