#
# COMP90024 Cluster and Cloud Computing Assignment2 - Team 42 
# 
# Authors: 
#
#  - Haoyu Gao (Student ID: 1141213)
#  - Runqi Zhao (Student ID: 1159719)
#  - Shukai Liu (Student ID: 1233459)
#  - Siyu Liu (Student ID：1094521)
#  - Wenjun Wang (Student ID: 1249890)
#
# Location: Melbourne
#
---
# Clone source code from github to virtual machine directory
- name: Clone source code from github to virtual machine directory
  git:
    repo: "https://github.com/90024-CCC-Assignment2/Assignment2.git"
    dest: ~/ccc_assignment2
  environment: "{{ proxy_env }}"
  become: true

# Ensure docker configuration directory exists or create it
- name: Ensure docker configuration directory exists or create it
  become: yes
  file:
    path: '~/.docker'
    state: 'directory'

# Ensure docker proxy for MRC exists
- name: Ensure docker proxy for MRC exists
  become: yes
  copy:
    content: "{{ docker_proxy_settings }}"
    dest: ~/.docker/config.json

# Build Docker image for Twitter Streaming (Harvester)
- name: Build Docker image for Twitter Streaming (Harvester)
  community.docker.docker_image:
    build:
      path: '~/ccc_assignment2/twitter_harvester'
      pull: yes
    name: cloud_assignment2/tweet-harvester
    tag: latest
    source: build
    force_source: yes
  become: yes
  environment: "{{ proxy_env }}"

# Stop and remove existing Docker container for Twitter Streaming (Harvester)
- name: Stop and remove existing Docker container for Twitter Streaming (Harvester)
  become: yes
  docker_container:
    name: twitter-harvester
    state: absent

# Create and start new docker container for Twitter Streaming (Harvester)
- name: Create and start new docker container for Twitter Streaming (Harvester)
  become: yes
  community.docker.docker_container:
    name: twitter-harvester
    image: cloud_assignment2/tweet-harvester
    state: started
    pull: false
    recreate: true
