#
# COMP90024 Cluster and Cloud Computing Assignment2 - Team 42 
# 
# Authors: 
#
#  - Haoyu Gao (Student ID: 1141213)
#  - Runqi Zhao (Student ID: 1159719)
#  - Shukai Liu (Student ID: 1233459)
#  - Siyu Liu (Student ID：1094521)
#  - Wenjun Wang (Student ID: 1249890)
#
# Location: Melbourne
#
---

# Add needed nodes to CouchDB cluster
- name: Add needed nodes to CouchDB cluster
  ansible.builtin.uri:
    url: http://{{ masternode }}:5984/_cluster_setup
    method: POST
    user: "{{ user }}"
    password: "{{ pass }}"
    force_basic_auth: yes
    status_code: 200, 201
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{\"action\": \"enable_cluster\", \"bind_address\": \"0.0.0.0\", \"username\":\"{{ user }}\", \"password\": \"{{ pass }}\", \"port\": \"5984\", \"remote_node\": \"{{ inventory_hostname }}\", \"node_count\": \"3\",\"remote_current_user\": \"{{ user }}\", \"remote_current_password\":\"{{ pass }}\"}"

# Join relevant nodes to CouchDB cluster
- name: Join relevant nodes to CouchDB cluster
  ansible.builtin.uri:
    url: http://{{ masternode }}:5984/_cluster_setup
    method: POST
    user: "{{ user }}"
    password: "{{ pass }}"
    force_basic_auth: yes
    status_code: 200, 201
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{\"action\":\"add_node\",\"host\":\"{{ inventory_hostname }}\",\"port\":\"5984\",\"username\":\"{{ user }}\",\"password\":\"{{ pass }}\"}"

# Send empty request to test errors
- name: Send empty request to test errors
  ansible.builtin.uri:
    url: http://{{ masternode }}:5984/
    method: GET
    user: "{{ user }}"
    password: "{{ pass }}"
    force_basic_auth: yes
  run_once: true

# Complete the process of Couchdb setup
- name: Complete the process of Couchdb setup
  ansible.builtin.uri:
    url: http://{{ masternode }}:5984/_cluster_setup
    method: POST
    user: "{{ user }}"
    password: "{{ pass }}"
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    status_code: 200, 201
    body_format: json
    body: "{\"action\":\"finish_cluster\"}"    
  run_once: true
