#
# COMP90024 Cluster and Cloud Computing Assignment2 - Team 42 
# 
# Authors: 
#
#  - Haoyu Gao (Student ID: 1141213)
#  - Runqi Zhao (Student ID: 1159719)
#  - Shukai Liu (Student ID: 1233459)
#  - Siyu Liu (Student ID：1094521)
#  - Wenjun Wang (Student ID: 1249890)
#
# Location: Melbourne
#
---

# Abandon existing CouchDB Docker containers
- name: Abandon existing CouchDB Docker containers
  become: yes
  community.docker.docker_container:
    name: couchdb
    state: absent

# Create and start new Docker containers for CouchDB
- name: Create and start new CouchDB Docker containers
  become: yes
  community.docker.docker_container:
    name: couchdb
    image: "ibmcom/couchdb3:{{ VERSION }}"
    state: started
    recreate: true
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - /data
    pull: yes
    env:
      COUCHDB_USER: "{{ user }}"
      COUCHDB_PASSWORD: "{{ pass }}"
      COUCHDB_SECRET: "{{ cookie }}"
      ERL_FLAGS: "-setcookie \"{{ cookie }}\" -name \"couchdb@{{ inventory_hostname }}\""